// angular-app/src/app/movies.component.ts
import { Component } from '@angular/core';
import { Movie } from './core';
import { Observable } from 'rxjs';
import { MovieService } from './movie.service';

@Component({
  selector: 'app-movie',
  template: `
    <div class="container columns">
      <div *ngIf="movies$ | async as movies" class="column is-8">
        <app-list-header
          title="My Movies"
          (refresh)="getMovies()"
          [showAdd]="showAdd"
        ></app-list-header>
        <div *ngIf="errorMessage">{{ errorMessage }}</div>
        <div *ngIf="!movies?.length && !errorMessage">Loading data ...</div>
        <ul class="list">
          <li
            role="presentation"
            *ngFor="let movie of movies; trackBy: trackByMovie; let i = index"
          >
            <div class="card">
              <div class="card-content">
                <div class="content movie-grid">
                  <label>Name:</label><span>{{ movie.name }}</span>
                  <label>Year:</label><span>{{ movie.year }}</span>
                  <label>Length:</label><span>{{ movie.length }}</span>
                </div>
              </div>
            </div>
          </li>
        </ul>
      </div>
    </div>
  `,
})
export class MovieComponent {
  errorMessage: string;
  showAdd = false;
  movies$: Observable<Movie[]>;

  constructor(private MovieService: MovieService) {
    this.movies$ = MovieService.entities$;
  }

  ngOnInit() {
    this.getMovies();
  }

  getMovies() {
    this.errorMessage = undefined;
    this.MovieService.getAll().subscribe(
      (_) => {
        /*.. do nothing for success.. */
      },
      (error: any) => (this.errorMessage = error.error.statusText),
    );
  }

  trackByMovie(index: number, movie: Movie): number {
    return movie.id;
  }
}

// svelte-app/src/Movies.svelte
<script lang="ts">
  import { ListHeader } from './components';

  import { onMount } from 'svelte';
  import { state, getMoviesAction } from './store';

  export const location: Object = {};

  let errorMessage: string = '';
  let { movies } = state;

  onMount(async () => await getMovies());

  async function getMovies() {
    errorMessage = '';
    try {
      await getMoviesAction();
    } catch (error) {
      errorMessage = 'Unauthorized';
    }
  }
  let showAdd: boolean = false;
</script>

<div class="content-container">
  <ListHeader title="My Movies" on:refresh={getMovies} {showAdd} />
  <div>
    {#if errorMessage}
      <div>{errorMessage}</div>
    {/if}
    {#if !$movies.length && !errorMessage}
      <div>Loading data ...</div>
    {/if}
    <ul class="list">
      {#each $movies as { id, name, year, length }, _i (id)}
        <li role="presentation">
          <div class="card">
            <div class="card-content">
              <div class="content movie-grid">
                <span class="label">Name:</span>
                <span>{name}</span>
                <span class="label">Year:</span>
                <span>{year}</span>
                <span class="label">Length:</span>
                <span>{length}</span>
              </div>
            </div>
          </div>
        </li>
      {/each}
    </ul>
  </div>
</div>
