// angular-app/src/app/heroes/heroes.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { Hero } from '../core';
import { HeroService } from './hero.service';

@Component({
  selector: 'app-heroes',
  template: `
    <div class="content-container">
      <app-list-header
        title="Heroes"
        (add)="enableAddMode()"
        (refresh)="getHeroes()"
      ></app-list-header>
      <div class="columns is-multiline is-variable">
        <div class="column is-8" *ngIf="heroes$ | async as heroes">
          <app-hero-list
            *ngIf="!selected"
            [heroes]="heroes"
            [errorMessage]="errorMessage"
            (selected)="select($event)"
            (deleted)="askToDelete($event)"
          ></app-hero-list>
          <app-hero-detail
            *ngIf="selected"
            [hero]="selected"
            (unselect)="clear()"
            (save)="save($event)"
          ></app-hero-detail>
        </div>
      </div>

      <app-modal
        class="modal-hero"
        [message]="message"
        [isOpen]="showModal"
        (handleNo)="closeModal()"
        (handleYes)="deleteHero()"
      ></app-modal>
    </div>
  `,
})
export class HeroesComponent implements OnInit {
  errorMessage: string;
  selected: Hero;
  heroes$: Observable<Hero[]>;
  message = '?';
  heroToDelete: Hero;
  showModal = false;

  constructor(private heroService: HeroService) {
    this.heroes$ = heroService.entities$;
  }

  ngOnInit() {
    this.getHeroes();
  }

  add(hero: Hero) {
    this.heroService.add(hero);
  }

  askToDelete(hero: Hero) {
    this.heroToDelete = hero;
    this.showModal = true;
    if (this.heroToDelete.name) {
      this.message = `Would you like to delete ${this.heroToDelete.name}?`;
    }
  }

  clear() {
    this.selected = null;
  }

  closeModal() {
    this.showModal = false;
  }

  deleteHero() {
    this.closeModal();
    if (this.heroToDelete) {
      this.heroService
        .delete(this.heroToDelete.id)
        .subscribe(() => (this.heroToDelete = null));
    }
    this.clear();
  }

  enableAddMode() {
    this.selected = <any>{};
  }

  async getHeroes() {
    this.errorMessage = undefined;
    this.heroService.getAll().subscribe(
      (_) => {
        /*.. do nothing for success.. */
      },
      (error: any) =>
        (this.errorMessage = error?.error?.message || 'Error occurred'),
    );
    this.clear();
  }

  save(hero: Hero) {
    if (this.selected && this.selected.name) {
      this.update(hero);
    } else {
      this.add(hero);
    }
  }

  select(hero: Hero) {
    this.selected = hero;
  }

  update(hero: Hero) {
    this.heroService.update(hero);
  }
}

// svelte-app/src/heroes/Heroes.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { ListHeader, Modal } from '../components';
  import HeroList from './HeroList.svelte';
  import HeroDetail from './HeroDetail.svelte';
  import {
    state,
    getHeroesAction,
    deleteHeroAction,
    addHeroAction,
    updateHeroAction,
  } from '../store';
  import { Hero } from '../models';
  import { logRouteLocation } from '../config';

  const { heroes } = state;

  export let location: Object = {};
  logRouteLocation(location);

  let selectedHero: Hero = undefined;
  let routePath = '/heroes';
  let title = 'Heroes';
  let heroToDelete: Hero = null;
  let message = '';
  let showModal = false;
  let errorMessage = '';

  onMount(async () => await getHeroes());

  function enableAddMode() {
    selectedHero = null;
  }

  function askToDelete({ detail: hero }) {
    heroToDelete = hero;
    showModal = true;
    if (heroToDelete.name) {
      message = `Would you like to delete ${heroToDelete.name}?`;
    }
  }

  function clear() {
    selectedHero = null;
  }

  function closeModal() {
    showModal = false;
  }

  async function deleteHero() {
    closeModal();
    if (heroToDelete) {
      console.log(`You said you want to delete ${heroToDelete.name}`);
      await deleteHeroAction(heroToDelete);
    }
    clear();
  }

  async function getHeroes() {
    errorMessage = undefined;
    try {
      await getHeroesAction();
    } catch (error) {
      errorMessage = error?.message || 'Error occurred';
    }
  }

  async function save({ detail: hero }) {
    console.log('hero changed', hero);
    if (hero.id) {
      await updateHeroAction(hero);
    } else {
      await addHeroAction(hero);
    }
  }

  function selectHero({ detail: hero }) {
    selectedHero = hero;
    console.log(`selected ${hero.name}`);
  }
</script>

<div class="content-container">
  <ListHeader
    {title}
    {routePath}
    on:add={enableAddMode}
    on:refresh={getHeroes}
  />
  <div class="columns is-multiline is-variable">
    {#if heroes}
      <div class="column is-8">
        {#if !selectedHero}
          <HeroList
            {errorMessage}
            heroes={$heroes}
            on:deleted={askToDelete}
            on:selected={selectHero}
          />
        {:else}
          <HeroDetail hero={selectedHero} on:unselect={clear} on:save={save} />
        {/if}
      </div>
    {/if}
  </div>

  <Modal
    {message}
    isOpen={showModal}
    on:handleNo={closeModal}
    on:handleYes={deleteHero}
  />
</div>
