// angular-app/src/app/heroes/hero-detail.component.ts
import {
  Component,
  Input,
  EventEmitter,
  OnChanges,
  Output,
  SimpleChanges,
  ChangeDetectionStrategy,
} from '@angular/core';

import { Hero } from '../core';

@Component({
  selector: 'app-hero-detail',
  template: `
    <div class="card edit-detail">
      <header class="card-header">
        <p class="card-header-title">
          {{ editingHero.name }}
          &nbsp;
        </p>
      </header>
      <div class="card-content">
        <div class="content">
          <div class="field" *ngIf="editingHero.id">
            <label class="label" for="id"> id </label>
            <input
              name="id"
              class="input"
              type="text"
              [(ngModel)]="editingHero.id"
              placeholder="e.g. HeroColleen"
              readOnly
            />
          </div>
          <div class="field">
            <label class="label" for="name"> name </label>
            <input
              name="name"
              class="input"
              type="text"
              [(ngModel)]="editingHero.name"
              placeholder="Oranges"
            />
          </div>
          <div class="field">
            <label class="label" for="description"> description </label>
            <input
              name="description"
              class="input"
              type="text"
              [(ngModel)]="editingHero.description"
              placeholder="box"
            />
          </div>
        </div>
      </div>
      <footer class="card-footer">
        <app-button-footer
          class="card-footer-item"
          [className]="'cancel-button'"
          [iconClasses]="'fas fa-undo'"
          (clicked)="clear()"
          label="Cancel"
          [item]="editingHero"
        ></app-button-footer>
        <app-button-footer
          class="card-footer-item"
          [className]="'save-button'"
          [iconClasses]="'fas fa-save'"
          (clicked)="saveHero()"
          label="Save"
          [item]="editingHero"
        ></app-button-footer>
      </footer>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeroDetailComponent implements OnChanges {
  @Input() hero: Hero;
  @Output() unselect = new EventEmitter<string>();
  @Output() save = new EventEmitter<Hero>();

  addMode = false;
  editingHero: Hero;

  ngOnChanges(changes: SimpleChanges) {
    if (this.hero && this.hero.id) {
      this.editingHero = { ...this.hero };
      this.addMode = false;
    } else {
      this.editingHero = {
        id: undefined,
        name: '',
        description: '',
      };
      this.addMode = true;
    }
  }

  clear() {
    this.unselect.emit();
  }

  saveHero() {
    this.save.emit(this.editingHero);
    this.clear();
  }
}

// svelte-app/src/heroes/HeroDetail.svelte
<script lang="ts">
  import { onMount, createEventDispatcher } from 'svelte';
  import { ButtonFooter } from '../components';
  import { Hero } from '../models';

  const dispatch = createEventDispatcher();
  export let hero: Hero;
  let editingHero = { ...hero };

  onMount(() => watchHero());

  function clear() {
    dispatch('unselect');
  }

  function saveHero() {
    dispatch('save', editingHero);
    clear();
  }

  function watchHero() {
    if (hero && hero.id) {
      editingHero = { ...hero };
    } else {
      editingHero = { id: undefined, name: '', description: '' };
    }
  }

  const cancelOptions = {
    className: 'card-footer-item cancel-button',
    label: 'Cancel',
    iconClasses: 'fas fa-undo',
  };

  const saveOptions = {
    className: 'card-footer-item save-button',
    label: 'Save',
    iconClasses: 'fas fa-save',
  };
</script>

<div class="card edit-detail">
  <header class="card-header">
    <p class="card-header-title">{editingHero.name}</p>
  </header>
  <div class="card-content">
    <div class="content">
      {#if editingHero.id}
        <div class="field">
          <label class="label" for="id">id</label>
          <input
            class="input"
            name="id"
            placeholder="99999"
            readonly
            type="text"
            bind:value={editingHero.id}
          />
        </div>
      {/if}
      <div class="field">
        <label class="label" for="name">name</label>
        <input
          class="input"
          name="name"
          placeholder="Oranges"
          type="text"
          bind:value={editingHero.name}
        />
      </div>
      <div class="field">
        <label class="label" for="description">description</label>
        <input
          class="input"
          name="description"
          placeholder="box"
          type="text"
          bind:value={editingHero.description}
        />
      </div>
    </div>
  </div>

  <footer class="card-footer">
    <ButtonFooter {...cancelOptions} item={editingHero} on:clicked={clear} />
    <ButtonFooter {...saveOptions} item={editingHero} on:clicked={saveHero} />
  </footer>
</div>
