// svelte-v/src/components/HeaderBarBrand.svelte
<div class="navbar-brand">
  <a
    class="navbar-item"
    href="https://svelte.dev/"
    target="_blank"
    rel="noopener noreferrer"
  >
    <img src="./svelte-icon.png" alt="Svelte" />
  </a>
  <router-link to="/" class="navbar-item nav-home">
    <span class="brand-first">TOUR</span>
    <span class="brand-second">OF</span>
    <span class="brand-third">HEROES</span>
    <span>, the movie edition</span>
  </router-link>
</div>

// angular-http-hard-way/src/app/core/components/header-bar-brand.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-header-bar-brand',
  template: `
    <div class="navbar-brand">
      <a
        class="navbar-item"
        href="https://angular.io/"
        target="_blank"
        rel="noopener noreferrer"
      >
        <i class="fab js-logo fa-angular fa-2x" aria-hidden="true"></i>
      </a>
      <a class="navbar-item nav-home" router-link="/">
        <span class="brand-first">TOUR</span>
        <span class="brand-second">OF</span>
        <span class="brand-third">HEROES</span>
        <span>, the movie edition (without Interceptors)</span>
      </a>
    </div>
  `,
})
export class HeaderBarBrandComponent {}
