// svelte-app/src/heroes/HeroList.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { ButtonFooter, CardContent } from '../components';
  import { Hero } from '../models';

  const dispatch = createEventDispatcher();
  export let heroes: Hero[] = [];
  export let errorMessage = '';

  function deleteHero(hero: Hero) {
    dispatch('deleted', hero);
  }

  function selectHero(hero: Hero) {
    dispatch('selected', hero);
  }

  const deleteOptions = {
    className: 'delete-item',
    label: 'Delete',
    iconClasses: 'fas fa-trash',
  };

  const editOptions = {
    className: 'edit-item',
    label: 'Edit',
    iconClasses: 'fas fa-edit',
  };
</script>

<div>
  {#if errorMessage}
    <div>{errorMessage}</div>
  {/if}
  {#if !heroes.length && !errorMessage}
    <div>Loading data ...</div>
  {/if}
  {#if heroes.length && !errorMessage}
    <ul class="list">
      {#each heroes as { id, name, description }, i (id)}
        <li role="presentation">
          <div class="card">
            <CardContent {name} {description} />
            <footer class="card-footer">
              <ButtonFooter
                {...deleteOptions}
                dataId={id}
                dataIndex={i}
                item={heroes[i]}
                on:clicked={() => deleteHero(heroes[i])}
              />
              <ButtonFooter
                {...editOptions}
                dataId={id}
                dataIndex={i}
                item={heroes[i]}
                on:clicked={() => selectHero(heroes[i])}
              />
            </footer>
          </div>
        </li>
      {/each}
    </ul>
  {/if}
</div>

// angular-app/src/app/heroes/hero-list.component.ts
import {
  Component,
  EventEmitter,
  Input,
  Output,
  ChangeDetectionStrategy,
} from '@angular/core';
import { Hero } from '../core';

@Component({
  selector: 'app-hero-list',
  template: `
    <div *ngIf="errorMessage">
      {{ errorMessage }}
    </div>
    <div *ngIf="!heroes?.length && !errorMessage">Loading data ...</div>
    <ul class="list" *ngIf="!errorMessage && heroes?.length">
      <li
        role="presentation"
        *ngFor="let hero of heroes; trackBy: trackByHero; let i = index"
      >
        <div class="card">
          <app-card-content
            [name]="hero.name"
            [description]="hero.description"
          ></app-card-content>
          <footer class="card-footer">
            <app-button-footer
              class="card-footer-item"
              [className]="'delete-item'"
              [iconClasses]="'fas fa-trash'"
              (clicked)="deleteHero($event)"
              label="Delete"
              [item]="hero"
            ></app-button-footer>
            <app-button-footer
              class="card-footer-item"
              [className]="'edit-item'"
              [iconClasses]="'fas fa-edit'"
              (clicked)="selectHero($event)"
              label="Edit"
              [item]="hero"
            ></app-button-footer>
          </footer>
        </div>
      </li>
    </ul>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class HeroListComponent {
  @Input() errorMessage = undefined;
  @Input() heroes: Hero[];
  @Output() deleted = new EventEmitter<Hero>();
  @Output() selected = new EventEmitter<Hero>();

  trackByHero(index: number, hero: Hero): number {
    return hero.id;
  }

  selectHero(hero: Hero) {
    this.selected.emit(hero);
  }

  deleteHero(hero: Hero) {
    this.deleted.emit(hero);
  }
}
