// angular-app/src/app/shared/button-footer.component.ts
import { Component, OnInit, Input, EventEmitter, Output } from '@angular/core';

@Component({
  standalone: false,
  selector: 'app-button-footer',
  template: `
    <button
      class="link"
      [ngClass]="className"
      [attr.aria-label]="label"
      tabindex="0"
      [attr.data-id]="item?.id"
      (click)="handleClick()"
    >
      <i [ngClass]="iconClasses"></i> <span>{{ label }}</span>
    </button>
  `,
})
export class ButtonFooterComponent implements OnInit {
  @Input() label;
  @Input() className;
  @Input() iconClasses;
  @Input() item;
  @Input() dataId;

  @Output() clicked = new EventEmitter<any>();

  ngOnInit() {}

  handleClick() {
    this.clicked.emit(this.item);
  }
}

// svelte-app/src/components/ButtonFooter.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';

  const dispatch = createEventDispatcher();

  export let item: object = undefined;
  export let className = '';
  export let label = '';
  export let dataIndex = 0;
  export let dataId: number = 0;
  export let iconClasses = '';

  function handleClick() {
    console.log(`button clicked ${JSON.stringify(item)}`);
    dispatch('clicked', item);
  }
</script>

<button
  class="link card-footer-item {className}"
  aria-label={label}
  tabindex="0"
  on:click={handleClick}
  data-index={dataIndex}
  data-id={dataId}
>
  <i class={iconClasses} />
  <span>{label}</span>
</button>
