// angular-app/src/app/villains/villain-list.component.ts
import {
  Component,
  EventEmitter,
  Input,
  Output,
  ChangeDetectionStrategy,
} from '@angular/core';
import { Villain } from '../core';

@Component({
  selector: 'app-villain-list',
  template: `
    <div *ngIf="errorMessage">
      {{ errorMessage }}
    </div>
    <div *ngIf="!villains?.length && !errorMessage">Loading data ...</div>
    <ul class="list">
      <li
        role="presentation"
        *ngFor="let villain of villains; trackBy: trackByVillain; let i = index"
      >
        <div class="card">
          <app-card-content
            [name]="villain.name"
            [description]="villain.description"
          ></app-card-content>
          <footer class="card-footer">
            <app-button-footer
              class="card-footer-item"
              [className]="'delete-item'"
              [iconClasses]="'fas fa-trash'"
              (clicked)="deleteVillain($event)"
              label="Delete"
              [item]="villain"
            ></app-button-footer>
            <app-button-footer
              class="card-footer-item"
              [className]="'edit-item'"
              [iconClasses]="'fas fa-edit'"
              (clicked)="selectVillain($event)"
              label="Edit"
              [item]="villain"
            ></app-button-footer>
          </footer>
        </div>
      </li>
    </ul>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class VillainListComponent {
  @Input() errorMessage = undefined;
  @Input() villains: Villain[];
  @Output() deleted = new EventEmitter<Villain>();
  @Output() selected = new EventEmitter<Villain>();

  trackByVillain(index: number, villain: Villain): number {
    return villain.id;
  }

  selectVillain(villain: Villain) {
    this.selected.emit(villain);
  }

  deleteVillain(villain: Villain) {
    this.deleted.emit(villain);
  }
}

// svelte-v/src/villains/VillainList.svelte
<script lang="ts">
  import { createEventDispatcher } from 'svelte';
  import { ButtonFooter, CardContent } from '../components';
  import { Villain } from '../models';

  const dispatch = createEventDispatcher();
  export let villains: Villain[] = [];
  export let errorMessage = '';

  function deleteVillain(villain: Villain) {
    dispatch('deleted', villain);
  }

  function selectVillain(villain: Villain) {
    dispatch('selected', villain);
  }

  const deleteOptions = {
    className: 'delete-item',
    label: 'Delete',
    iconClasses: 'fas fa-trash',
  };

  const editOptions = {
    className: 'edit-item',
    label: 'Edit',
    iconClasses: 'fas fa-edit',
  };
</script>

<div>
  {#if errorMessage}
    <div>{errorMessage}</div>
  {/if}
  {#if !villains.length && !errorMessage}
    <div>Loading data ...</div>
  {/if}
  {#if villains.length && !errorMessage}
    <ul class="list">
      {#each villains as { id, name, description }, i (id)}
        <li role="presentation">
          <div class="card">
            <CardContent {name} {description} />
            <footer class="card-footer">
              <ButtonFooter
                {...deleteOptions}
                dataId={id}
                dataIndex={i}
                item={villains[i]}
                on:clicked={() => deleteVillain(villains[i])}
              />
              <ButtonFooter
                {...editOptions}
                dataId={id}
                dataIndex={i}
                item={villains[i]}
                on:clicked={() => selectVillain(villains[i])}
              />
            </footer>
          </div>
        </li>
      {/each}
    </ul>
  {/if}
</div>
