// angular-app/src/app/villains/villain-detail.component.ts
import {
  Component,
  Input,
  EventEmitter,
  OnChanges,
  Output,
  SimpleChanges,
  ChangeDetectionStrategy,
} from '@angular/core';

import { Villain } from '../core';

@Component({
  selector: 'app-villain-detail',
  template: `
    <div class="card edit-detail">
      <header class="card-header">
        <p class="card-header-title">
          {{ editingVillain.name }}
          &nbsp;
        </p>
      </header>
      <div class="card-content">
        <div class="content">
          <div class="field" *ngIf="editingVillain.id">
            <label class="label" for="id"> id </label>
            <input
              name="id"
              class="input"
              type="text"
              [(ngModel)]="editingVillain.id"
              placeholder="e.g. VillainColleen"
              readOnly
            />
          </div>
          <div class="field">
            <label class="label" for="name"> name </label>
            <input
              name="name"
              class="input"
              type="text"
              [(ngModel)]="editingVillain.name"
              placeholder="Oranges"
            />
          </div>
          <div class="field">
            <label class="label" for="description"> description </label>
            <input
              name="description"
              class="input"
              type="text"
              [(ngModel)]="editingVillain.description"
              placeholder="box"
            />
          </div>
        </div>
      </div>
      <footer class="card-footer">
        <app-button-footer
          class="card-footer-item"
          [className]="'cancel-button'"
          [iconClasses]="'fas fa-undo'"
          (clicked)="clear()"
          label="Cancel"
          [item]="editingVillain"
        ></app-button-footer>
        <app-button-footer
          class="card-footer-item"
          [className]="'save-button'"
          [iconClasses]="'fas fa-save'"
          (clicked)="saveVillain()"
          label="Save"
          [item]="editingVillain"
        ></app-button-footer>
      </footer>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class VillainDetailComponent implements OnChanges {
  @Input() villain: Villain;
  @Output() unselect = new EventEmitter<string>();
  @Output() save = new EventEmitter<Villain>();

  addMode = false;
  editingVillain: Villain;

  ngOnChanges(changes: SimpleChanges) {
    if (this.villain && this.villain.id) {
      this.editingVillain = { ...this.villain };
      this.addMode = false;
    } else {
      this.editingVillain = {
        id: undefined,
        name: '',
        description: '',
      };
      this.addMode = true;
    }
  }

  clear() {
    this.unselect.emit();
  }

  saveVillain() {
    this.save.emit(this.editingVillain);
    this.clear();
  }
}

// svelte-app/src/villains/VillainDetail.svelte
<script lang="ts">
  import { onMount, createEventDispatcher } from 'svelte';
  import { ButtonFooter } from '../components';
  import { Villain } from '../models';

  const dispatch = createEventDispatcher();
  export let villain: Villain;
  let editingVillain = { ...villain };

  onMount(() => watchVillain());

  function clear() {
    dispatch('unselect');
  }

  function saveVillain() {
    dispatch('save', editingVillain);
    clear();
  }

  function watchVillain() {
    if (villain && villain.id) {
      editingVillain = { ...villain };
    } else {
      editingVillain = { id: undefined, name: '', description: '' };
    }
  }

  const cancelOptions = {
    className: 'card-footer-item cancel-button',
    label: 'Cancel',
    iconClasses: 'fas fa-undo',
  };

  const saveOptions = {
    className: 'card-footer-item save-button',
    label: 'Save',
    iconClasses: 'fas fa-save',
  };
</script>

<div class="card edit-detail">
  <header class="card-header">
    <p class="card-header-title">{editingVillain.name}</p>
  </header>
  <div class="card-content">
    <div class="content">
      {#if editingVillain.id}
        <div class="field">
          <label class="label" for="id">id</label>
          <input
            class="input"
            name="id"
            placeholder="99999"
            readonly
            type="text"
            bind:value={editingVillain.id}
          />
        </div>
      {/if}
      <div class="field">
        <label class="label" for="name">name</label>
        <input
          class="input"
          name="name"
          placeholder="Oranges"
          type="text"
          bind:value={editingVillain.name}
        />
      </div>
      <div class="field">
        <label class="label" for="description">description</label>
        <input
          class="input"
          name="description"
          placeholder="box"
          type="text"
          bind:value={editingVillain.description}
        />
      </div>
    </div>
  </div>

  <footer class="card-footer">
    <ButtonFooter {...cancelOptions} item={editingVillain} on:clicked={clear} />
    <ButtonFooter
      {...saveOptions}
      item={editingVillain}
      on:clicked={saveVillain}
    />
  </footer>
</div>
