// svelte-app/src/products/Products.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { ListHeader, Modal } from '../components';
  import ProductList from './ProductList.svelte';
  import ProductDetail from './ProductDetail.svelte';
  import {
    state,
    getProductsAction,
    deleteProductAction,
    addProductAction,
    updateProductAction,
  } from '../store';
  import { Product } from '../models';
  import { logRouteLocation } from '../config';

  const { products } = state;

  export let location: Object = {};
  logRouteLocation(location);

  let selectedProduct: Product = undefined;
  let routePath = '/Eproducts';
  let title = 'Heroes';
  let productToDelete: Product = null;
  let message = '';
  let showModal = false;
  let errorMessage = '';

  onMount(async () => await getProducts());

  function enableAddMode() {
    selectedProduct = null;
  }

  function askToDelete({ detail: product }) {
    productToDelete = product;
    showModal = true;
    if (productToDelete.name) {
      message = `Would you like to delete ${productToDelete.name}?`;
    }
  }

  function clear() {
    selectedProduct = null;
  }

  function closeModal() {
    showModal = false;
  }

  async function deleteProduct() {
    closeModal();
    if (productToDelete) {
      console.log(`You said you want to delete ${productToDelete.name}`);
      await deleteProductAction(productToDelete);
    }
    clear();
  }

  async function getProducts() {
    errorMessage = undefined;
    try {
      await getProductsAction();
    } catch (error) {
      errorMessage = 'Unauthorized';
    }
  }

  async function save({ detail: product }) {
    console.log('product changed', product);
    if (product.id) {
      await updateProductAction(product);
    } else {
      await addProductAction(product);
    }
  }

  function selectProduct({ detail: product }) {
    selectedProduct = product;
    console.log(`selected ${product.name}`);
  }
</script>

<div class="content-container">
  <ListHeader
    {title}
    {routePath}
    on:add={enableAddMode}
    on:refresh={getProducts}
  />
  <div class="columns is-multiline is-variable">
    {#if products}
      <div class="column is-8">
        {#if !selectedProduct}
          <ProductList
            {errorMessage}
            products={$products}
            on:deleted={askToDelete}
            on:selected={selectProduct}
          />
        {:else}
          <ProductDetail
            product={selectedProduct}
            on:unselect={clear}
            on:save={save}
          />
        {/if}
      </div>
    {/if}
  </div>

  <Modal
    {message}
    isOpen={showModal}
    on:handleNo={closeModal}
    on:handleYes={deleteProduct}
  />
</div>

// angular-app/src/app/products/products.component.ts
import { Component, OnInit } from '@angular/core';
import { Observable } from 'rxjs';
import { Product } from '../core';
import { ProductService } from './product.service';

@Component({
  selector: 'app-products',
  template: `
    <div class="content-container">
      <app-list-header
        title="Heroes"
        (add)="enableAddMode()"
        (refresh)="getProducts()"
      ></app-list-header>
      <div class="columns is-multiline is-variable">
        <div class="column is-8" *ngIf="products$ | async as products">
          <app-product-list
            *ngIf="!selected"
            [products]="products"
            [errorMessage]="errorMessage"
            (selected)="select($event)"
            (deleted)="askToDelete($event)"
          ></app-product-list>
          <app-product-detail
            *ngIf="selected"
            [product]="selected"
            (unselect)="clear()"
            (save)="save($event)"
          ></app-product-detail>
        </div>
      </div>

      <app-modal
        class="modal-product"
        [message]="message"
        [isOpen]="showModal"
        (handleNo)="closeModal()"
        (handleYes)="deleteProduct()"
      ></app-modal>
    </div>
  `,
})
export class ProductsComponent implements OnInit {
  errorMessage: string;
  selected: Product;
  products$: Observable<Product[]>;
  message = '?';
  productToDelete: Product;
  showModal = false;

  constructor(private productService: ProductService) {
    this.products$ = productService.entities$;
  }

  ngOnInit() {
    this.getProducts();
  }

  add(product: Product) {
    this.productService.add(product);
  }

  askToDelete(product: Product) {
    this.productToDelete = product;
    this.showModal = true;
    if (this.productToDelete.name) {
      this.message = `Would you like to delete ${this.productToDelete.name}?`;
    }
  }

  clear() {
    this.selected = null;
  }

  closeModal() {
    this.showModal = false;
  }

  deleteProduct() {
    this.closeModal();
    if (this.productToDelete) {
      this.productService
        .delete(this.productToDelete.id)
        .subscribe(() => (this.productToDelete = null));
    }
    this.clear();
  }

  enableAddMode() {
    this.selected = <any>{};
  }

  async getProducts() {
    this.errorMessage = undefined;
    this.productService.getAll().subscribe(
      (_) => {
        /*.. do nothing for success.. */
      },
      (error: any) => (this.errorMessage = error.error.statusText),
    );
    this.clear();
  }

  save(product: Product) {
    if (this.selected && this.selected.name) {
      this.update(product);
    } else {
      this.add(product);
    }
  }

  select(product: Product) {
    this.selected = product;
  }

  update(product: Product) {
    this.productService.update(product);
  }
}
